source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'
gem 'sass-rails', "~> 3.1.0.rc"
gem 'coffee-script'
gem 'uglifier'
gem 'jquery-rails'
gem 'devise', ' 1.4.2'
gem 'therubyracer-heroku', '0.8.1.pre3'
gem 'friendly_id', '~> 3.3.0.alpha2'
gem 'thin'
gem 'pg'
gem 'haml'

group :test, :development do
  gem 'ruby-debug19', :require => 'ruby-debug'
  gem 'hpricot'
  gem 'ruby_parser'
  gem 'heroku'
  gem 'launchy'
  gem 'sqlite3'
  gem 'spork', '0.9.0.rc9'
  gem 'rspec-rails', '>= 2.6.1'
  gem 'factory_girl_rails', '>= 1.1.beta1'
  gem 'cucumber-rails', '1.0.1'
  gem 'email_spec'
  gem 'capybara', '>= 1.0.0'
  gem 'database_cleaner', '>= 0.6.7'
  gem 'rb-inotify'
  gem 'libnotify'
  gem 'guard', '0.5.0'
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'guard-spork'
end

