source 'http://rubygems.org'

gem 'rails', '3.1.3'
gem 'sass-rails'
gem 'coffee-script'
gem 'uglifier'
gem 'jquery-rails'
gem 'devise', '1.4.7'
gem 'therubyracer', '>= 0.9.9'
gem 'thin'
gem 'haml'
gem 'simple_form'
gem 'client_side_validations', '3.1.3'
gem 'faker'
gem 'kaminari'
gem 'gravatar_image_tag', '1.0.0'

group :production do
  gem 'pg'
end

group :test, :development do
  gem 'ruby-debug19', :require => 'ruby-debug'
  gem 'hpricot'
  gem 'ruby_parser'
  gem 'heroku'
  gem 'launchy', '2.0.5'
  gem 'sqlite3'
  gem 'spork', '0.9.0.rc9'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'email_spec'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'rb-inotify'
  gem 'libnotify'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'guard-spork'
  gem 'guard-livereload'
  gem 'guard-rails'
end

