development:
  adapter: postgresql
  database: merciboq_development
  pool: 5
  username:
  password: tastywave

test: &test
  adapter: postgresql
  database: merciboq_test
  pool: 5
  username:
  password: tastywave

production:
  adapter: postgresql
  database: merciboq_production
  pool: 5
  username:
  password: tastywave

cucumber:
  <<: *test

