development:
  adapter: postgresql
  database: merciboq_development
  pool: 5
  username: frederick
  password: tastywave

test: &test
  adapter: postgresql
  database: merciboq_test
  pool: 5
  username: frederick
  password: tastywave

production:
  adapter: postgresql
  database: merciboq_production
  pool: 5
  username: postgres
  password: 

cucumber:
  <<: *test

